language: objective-c
osx_image: xcode8.3
xcode_workspace: MDFInternationalizationExample.xcworkspace
xcode_scheme: MDFInternationalizationTests
xcode_sdk: iphonesimulator10.3
destination: "OS=10.3,name=iPhone 5"
script: xcodebuild -workspace "$TRAVIS_XCODE_WORKSPACE" -scheme "$TRAVIS_XCODE_SCHEME" -destination "$TRAVIS_XCODE_WORKSPACE" build test
